<?php

namespace AppBundle\Repository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository
{
/*        public function categories_without_parent()
    {
        $conn = $this->getEntityManager()->getConnection();
        $sql = 'SELECT title FROM category where parent_id is NULL';
        $stmt = $conn->prepare($sql);
        $stmt->execute();
        //var_dump($stmt->fetchAll());die;

        return $stmt->fetchAll();
    }

    public function subcategories_name()
    {
        $conn = $this->getEntityManager()->getConnection();
        $sql = 'SELECT title FROM category where parent_id is not NULL';
        $stmt = $conn->prepare($sql);
        $stmt->execute();
        //var_dump($stmt->fetchAll());die;

        return $stmt->fetchAll();
    }*/
}