<?php

namespace AppBundle\Repository;

/**
 * Product_RatingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Product_RatingRepository extends \Doctrine\ORM\EntityRepository
{
/*    public function get_comments($id)
    {
        $conn = $this->getEntityManager()->getConnection();
        $sql = 'SELECT comment, rating FROM product__rating WHERE product_id'.' ='.$id;
        $stmt = $conn->prepare($sql);
        $stmt->execute();
        //var_dump($stmt->fetchAll());die;

        return $stmt->fetchAll();
    }*/
}
