<?php

namespace AppBundle\Repository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllActive()
    {
        $qb = $this->createQueryBuilder('p');
        $now = new \DateTime();
        return $qb->where('p.dateEndBid > :enddate')
            ->setParameter('enddate', $now)
            ->getQuery()->getResult();
    }
}